# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://ktcer.github.io/
date_format: "ordinal"
title: 铁矿
subtitle: "一切的成功都源于一个梦想和毫无依据的自信，坚持就是胜利。"
description: "ktcer的个人博客"
keywords: ktcerr kuangtiecheng, ktc2013, buptkuang
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
source_code: https://github.com/ktcer/ktcer.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: kuangtiecheng
organization: 北京邮电大学, Inc.
organization_url: http://write.blog.csdn.net/postlist
location: Beijing, China
email: kuagtiecheng68@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: ktcer
weibo_username: 旷铁成
zhihu_username: ktcer


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: ktcer
disqus_username: ktcer

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
